environments:
  development:
    kinematics:
      inverse_kinematics:
        num_attempts: 5
    logging:
      level: DEBUG
  production:
    logging:
      level: INFO
    performance:
      log_statistics: true
  testing:
    validation:
      max_samples: 50
kinematics:
  inverse_kinematics:
    damping: 0.01
    dq_max: 0.2
    max_iters: 300
    num_attempts: 10
    pos_tol: 1.0e-06
    rot_tol: 1.0e-06
    step_scale: 0.5
logging:
  backup_count: 5
  file: robot_kinematics.log
  level: INFO
  max_size_mb: 10
performance:
  log_statistics: true
  max_ik_time: 1.0
  warning_thresholds:
    ik_success_rate: 0.95
    position_error: 0.01
    rotation_error: 0.02
robot:
  base_link: link0
  ee_link: tcp
  joint_limits_deg:
  - - -180
    - 180
  - - -180
    - 180
  - - -180
    - 180
  - - -180
    - 180
  - - -180
    - 180
  - - -180
    - 180
  urdf_path: rb3_730es_u.urdf
  workspace_limits:
    x_range:
    - -1.0
    - 1.0
    y_range:
    - -1.0
    - 1.0
    z_range:
    - 0.0
    - 1.5
robot_controller:
  ip_address: 192.168.1.100
  port: 30003
  timeout: 5.0
  units:
    joint_angles: degrees
    orientations: radians
    positions: millimeters
validation:
  max_samples: 100
  position_tolerance: 0.005
  rotation_tolerance: 0.01
